version: '2.0'
services:
  log_generator:
    image: jmasseydd/workshop21:v0.3
    environment:
    - DD_API_KEY=${DD_API_KEY}
    - FLAWS_DATASET=True
    - ASSUME_ROLE_ATTACK=True
    - CREATE_BUCKET=True
    - PUBLIC_ANONYMOUS_S3=True
    - AUTHENTICATED_S3_ACCESS=True
    - S3_ACL=True
    - ASSUME_ROLE=True