version: '3'
services:
  agent:
    image: "datadog/agent:7.21.1"
    environment:
      - DD_API_KEY
      - DD_APM_ENABLED=true
# add agent env variables
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.team":"team"}
      - DD_TAGS='env:ruby-shop'
    ports:
      - "8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
# add agent log labels
  discounts:
    environment:
      - FLASK_APP=discounts.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DD_SERVICE=discounts-service
      - DD_AGENT_HOST=agent
# add discounts env variables
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_VERSION=1.1
    image: "ddtraining/discounts-service-fixed:latest"
    command: ddtrace-run flask run --port=5001 --host=0.0.0.0
    ports:
      - "5001:5001"
    depends_on:
      - agent
      - db
# add discounts log labels 
  frontend:
    environment:
      - DD_AGENT_HOST=agent
# add frontend env variables
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_SERVICE=store-frontend
      - DB_USERNAME
      - DB_PASSWORD
      - DD_VERSION=1.1
      - DD_CLIENT_TOKEN
      - DD_APPLICATION_ID
    image: "ddtraining/ecommerce-frontend:latest"
    command: sh docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - agent
      - db
      - discounts
      - advertisements
# add frontend log labels
  advertisements:
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DD_SERVICE=advertisements-service
      - DD_AGENT_HOST=agent
# add ads env variables
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_VERSION=1.0
    image: "ddtraining/advertisements-service:latest"
    command: ddtrace-run flask run --port=5002 --host=0.0.0.0
    ports:
      - "5002:5002"
    depends_on:
      - agent
      - db
# add ads log labels
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
# add postgres log labels
