#!/bin/bash
show_progress()
{
  local -r pid="${1}"
  local -r delay='1'

  while true; do 
    grep -i "complete" status.txt &> /dev/null
    if [[ "$?" -ne 0 ]]; then     
        sleep "${delay}" 
    else
      break
    fi
    
  done
}
while [ ! -f "status.txt" ]; do
  sleep 0.3
done
show_progress
if [ ! -f "/root/provisioned" ]; then
  touch /root/provisioned
  printf "Provisioning complete.\n\n"
else
  printf "\n\nWelcome back to the training lab.\n\n"
fi
printf "Finalizing app deployment.\n\n"
until $(curl -o /dev/null -s -I -f http://localhost:3000); do
  sleep 1
done
printf 'OK, the training environment is installed and ready to go.\n\n'