version: '3'
services:
  agent:
    image: "datadog/agent:6.13.0"
    environment:
      - DD_API_KEY
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS='env:ruby-shop'
# add agent env variables
# add agent trace port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
# add agent log labels
  discounts:
    environment:
      - FLASK_APP=discounts.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DATADOG_SERVICE_NAME=discounts-service
# add discounts env variables
    image: "burningion/ecommerce-spree-discounts:latest"
# add discounts flask server command
    ports:
      - "5001:5001"
    volumes:
      - "./discounts-service:/app"
    depends_on:
      - agent
      - db
# add discounts log labels 
  frontend:
    environment:
      - DB_USERNAME
      - DB_PASSWORD
# add frontend env variables
    image: "burningion/ecommerce-spree-observability:cpu-workaround"
    command: sh docker-entrypoint.sh
    ports:
      - "3000:3000"
    depends_on:
      - agent
      - db
      - discounts
      - advertisements
    volumes:
      - ./store-frontend:/spree/sandbox
# add frontend log labels
  advertisements:
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DATADOG_SERVICE_NAME=advertisements-service
# add ads env variables
    image: "burningion/ecommerce-spree-ads:latest"
# add ads flask server command
    ports:
      - "5002:5002"
    volumes:
      - "./ads-service:/app"
    depends_on:
      - agent
      - db
# add ads log labels
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    labels:
      com.datadoghq.ad.logs: '[{"source": "postgres", "service": "postgres"}]'